# Generated by Django 4.2.5 on 2023-10-04 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_order_orderproducts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='peyment_status',
            new_name='payment_status',
        ),
    ]
